blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='blog_url_name'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
]

main/urls.py
from django.conf.urls import url
from . import views

# https://stackoverflow.com/questions/340888/navigation-in-django

app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name='index_url_name'),
    url(r'^links/$', views.links, name='links_url_name'),
    url(r'^people/$', views.people, name='people_url_name'),
    url(r'^software/$', views.software, name='software_url_name'),
    url(r'^asa/$', views.asa, name='asa_url_name')

    # url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'), # here
    # url(r'^event/new/$', views.event, name='event_new'),
    # url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

# for summernote
from django.conf import settings
from django.conf.urls.static import static

import main

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('main.urls')),
]

handler404 = main.views.handler404
handler500 = main.views.handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
# from tinymce.models import HTMLField

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    # text = models.TextField()
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    # published_date = models.DateTimeField(blank=True, null=True)

    # def publish(self):
        # self.published_date = timezone.now()
        # self.save()

    def __str__(self):
        return self.title

main/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post
from django.shortcuts import render, get_object_or_404


def post_list(request):
    time = timezone.now()
    posts = Post.objects.order_by('-created_date')
    return render(request, 'blog/post_list.html', {'posts': posts, 'time': time})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect


# Create your views here.
def index(request):
    return render(request, 'main/index.html')

def people(request):
    return render(request, 'main/people.html')

def software(request):
    return render(request, 'main/software.html')

def links(request):
    return render(request, 'main/links.html')

def asa(request):
    return render(request, 'main/asa.html')

def handler404(request, *args, **kwargs):
    return render(request, 'main/404.html', status=404)

def handler500(request):
    return render(request, 'main/500.html', status=500)

blog/templates/blog/base.html
{% load staticfiles %} 
<html> 
  <head> 
    <title>CP Blog</title> 
    <link href="//fonts.googleapis.com/css?Tangerine:bold,bolditalic|Inconsolata:italic|Droid+Sans" rel="stylesheet" type="text/css"> 
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"> 
    <link rel="stylesheet" href="{% static 'css/blog.css' %}"> 
  </head> 
  <body> 
    <div class="page-header"> 
      <h1><a href="/">Clever Programmer Blog</a></h1> 
    </div> 
    <div class="content container"> 
      <div class="row"> 
        <div class="col-md-8"> 
          {% block content %} 
          {% endblock %} 
        </div> 
      </div> 
    </div> 
  </body> 
</html>

blog/templates/blog/post_detail.html
{% extends 'main/base.html' %} 

{% block content %}
<h1>{{ post.title }}</h1>
{{ post.created_date }} by {{ post.author.first_name }} {{ post.author.last_name }}
<div class="my-4">
	{{ post.content | safe }}
</div>

<a href="{% url 'blog_url_name' %}">Back</a>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Blog posts</h1>


{% for post in posts %}
<div class="post">
	<h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
	{{ post.created_date }} by {{ post.author.first_name }} {{ post.author.last_name }}
	<!-- 	{{ post.content | safe }} -->
	<!-- <p>{{ post.text | linebreaksbr }}</p> -->
</div>
{% endfor %}
{% endblock %}

main/templates/main/asa.html
{% extends 'main/base.html' %}

{% block title %}
UVM's ASA Student Chapter
{% endblock %}

{% block content %}
	<h1>UVM's ASA Student Chapter</h1>

<p>We are UVM's official American Statistical Association (ASA) chapter. Here are some ASA-related links:</p>
<ul>
  <li><a href="https://www.amstat.org/ASA/Membership/Student-Chapters.aspx">https://www.amstat.org/ASA/Membership/Student-Chapters.aspx</a></li>
  <li><a href="https://thisisstatistics.org/">https://thisisstatistics.org/</a></li>
  <li><a href="https://www.amstat.org/">https://www.amstat.org/</a></li>
</ul>


{% endblock %}

main/templates/main/base.html
{% load staticfiles %}


<!-- for links -->
{% load tags %}

{% url 'main:index_url_name' as index %}
{% url 'main:software_url_name' as software %}
{% url 'blog_url_name' as blog %}
{% url 'main:links_url_name' as links %}
{% url 'main:people_url_name' as people %}
{% url 'main:asa_url_name' as asa %}



<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->

		<link rel="stylesheet"
			  href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cosmo/bootstrap.min.css">

		<link rel="shortcut icon" type="image/png" href="{% static 'main/images/square-black-small.png' %}"/>

		
		<!-- custom css -->
		<link rel="stylesheet" type="text/css" href="{% static 'main/css/custom.css' %}">
		<!-- <title>UVM Stats and DS Club</title> -->
		<title>{% block title %}{% endblock %}</title>

		<!-- bootstrap only needs small jquery, but fullcalendar (index.html) needs full version -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		
	
		





			
		{% block head %}{% endblock %}
	</head>
	<body>

		
		
		<header class="navbar fixed-top navbar-light" id="header">

			<!-- navbar brand -->
			<a class="navbar-brand d-flex flex-row align-items-center" id="header" href="{{ index }}">
				<img class="d-flex pr-2" src="{% static 'main/images/square-medium.png' %}" width="50">
				<div class="d-flex">UVM Stats and DS Club</div>
			</a>


			<!-- collapse button -->
			<button class="navbar-toggler" type="button" data-toggle="collapse"
					data-target="#navbarCollapse" aria-controls="navbarCollapse"
						   aria-expanded="false" aria-label="Toggle navigation">
				<!-- <small class="pr-2">Menu</small> -->
				<span class="navbar-toggler-icon"></span>
			</button>



			<!-- links list -->			
			<nav class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav">

					<li class="nav-item">
						<a class="{% active request index %} nav-link" href="{{ index }}">Home</a>
					</li>

					<li class="nav-item">
						<a class="{% active request blog %} nav-link" href="{{ blog }}">Blog</a>
					</li>

					<li class="nav-item">
						<a class="{% active request people %} nav-link" href="{{ people }}">People</a>
					</li>
					
					<li class="nav-item">
						<a class="{% active request asa %} nav-link" href="{{ asa }}">ASA Student Chapter</a>
					</li>

					<li class="nav-item">
						<a class="{% active request links %} nav-link" href="{{ links }}">Useful Links</a>
					</li>
					
					<li class="nav-item">
						<a class="{% active request software %} nav-link" href="{{ software }}">Software</a>
					</li>

					

					

				</ul>
			</nav>
			
		</header>

		<main class="container" id="main-content">
			{% block content %}
			{% endblock %}
		</main>


		<footer class="footer container-fluid">
			<p>Designed by Nicholas Hanoian</p>
		</footer>
		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		


		<script>
		 $(document).ready(function() {
			 // any links with a fully qualified address open in a new tab
			 $( 'a[href^="http://"]' ).attr( 'target','_blank' );
			 $( 'a[href^="https://"]' ).attr( 'target','_blank' );

		 });
		</script>
		
		{% block script %}
		{% endblock %}
	</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load staticfiles %}

{% block head %}
<link href= "{% static 'main/fullcalendar/fullcalendar.min.css' %}" rel='stylesheet' />
<link href= "{% static 'main/fullcalendar/fullcalendar.print.min.css' %}" rel='stylesheet' media='print' />
<script src="{% static 'main/fullcalendar/lib/moment.min.js' %}"></script>
<!-- already loaded jquery in base.html -->
<!-- <script src="{% static 'main/fullcalendar/lib/jquery.min.js' %}"></script> -->
<script src="{% static 'main/fullcalendar/fullcalendar.min.js' %}" ></script>
<script src="{% static 'main/fullcalendar/gcal.min.js' %}"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


{% endblock %}

{% block title %}
UVM Stats and DS Club
{% endblock %}


{% block content %}
<div class="mb-5 text-center">
	<img src="{% static 'main/images/long-large.png' %}" class="img-fluid">
</div>

<div class="text-center">
	<h1>Welcome to the Statistics and Data Science club website!</h1>
</div>



<p>Hello, and welcome to Statistics and Data Science Club! If you are interested in getting involved with numbers, then you've come to the right place! With biweekly meetings and planned events, we strive to introduce members to the possibilities open to them in the field of stats and data. Everyone is welcome to join, regardless of major.</p>

<p>Come join the fun at our next meeting in the Student Club Space at Innovation Hall, E327!</p>

<div class="mt-5" id="calendar"></div>




<!-- popup for calendar events -->
<div id="fullCalModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 id="modalTitle" class="modal-title"></h4>
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
			</div>
			<!-- body -->
			<div class="modal-body container">
				<div class="row">
					<p class="col-1"><i class="far fa-clock"></i></p>
					<p class="col" id="modalTime"></p>
				</div>

				<div class="row" id="locationRow">
					<p class="col-1"><i class="fas fa-map-marker-alt"></i></p>
					<p class="col" id="modalLocation"></p>
				</div>
				
				<div class="row" id="descriptionRow">
					<p class="col-1"><i class="fas fa-align-left"></i></p>
					<p class="col" id="modalDescription"></p>
				</div>

			</div>

			
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<a class="btn btn-primary" id="eventUrl" target="_blank">Event Page</a>
			</div>
		</div>
	</div>
</div>

<script>
 

 $(document).ready(function() {

	 $('#calendar').fullCalendar({

		 header: {
			 left: 'prev,next today',
			 center: 'title',
			 right: 'month,listYear'
		 },
		 themeSystem: 'bootstrap4',
		 /* 		 displayEventTime: false, // don't show the time column in list view */

		 // To make your own Google API key, follow the directions here:
					  // http://fullcalendar.io/docs/google_calendar/
		 // statclub@uvm.edu api key
		 googleCalendarApiKey: 'AIzaSyBrbsv3gRkz-Oldoc1-4iVOcsHHQxZyLEI',

		 // US Holidays
		 events: {
			 googleCalendarId: 'statclub@uvm.edu'
		 },
		 

		 eventClick:  function(event, jsEvent, view) {
			 console.log(event);

			 $('#modalTitle').html(event.title);
			 if (event.description) {
				 $('#modalDescription').html(event.description);
				 $('#descriptionRow').show();
			 } else {
				 $('#descriptionRow').hide();
			 }
			 if (event.location) {
				 $('#modalLocation').html(event.location);
				 $('#locationRow').show();
			 } else {
				 $('#locationRow').hide();
			 }


			 let dateOptions = { weekday: 'long', month: 'long', day: 'numeric' };
			 let timeOptions = { hour12: true, hour: "numeric", minute: "numeric" };

			 let startDate = new Date(event.start._i);
			 let endDate = new Date(event.end._i);

			 let startDay = startDate.toLocaleDateString('en-US', dateOptions);
			 let endDay = endDate.toLocaleDateString('en-US', dateOptions);

			 let startTime = startDate.toLocaleString('en-US', timeOptions).toLowerCase();
			 let endTime = endDate.toLocaleString('en-US', timeOptions).toLowerCase();


			 console.log(event);
			 /* 			 console.log(endDay); */
			 if (startDay === endDay) {
				 $('#modalTime').html(startDay + ' ⋅ ' + startTime + ' – ' + endTime);				 
			 } else {
				 $('#modalTime').html(startDay + ', ' + startTime + ' – ' + endDay + ', ' + endTime);
			 }

			 

			 $('#eventUrl').attr('href', event.url);
			 $('#fullCalModal').modal();
			 return false;
		 },

	 });

 });

</script>




{% endblock %}

main/templates/main/links.html
{% extends 'main/base.html' %}

{% block title %}
	Useful Links
{% endblock %}

{% block content %}
	<h1>Useful Links</h1>
	<p>Here's some links to other pages that Statistics and Data Science majors might find useful.</p>

	<h2>UVM and CEMS Career Resources</h2>
	<ul>
	  <li><a href="https://www.uvm.edu/career">https://www.uvm.edu/career</a></li>
	  <li><a href="https://www.uvm.edu/cems/career_readiness_program">https://www.uvm.edu/cems/career_readiness_program</a></li>
	  <li><a href="https://www.uvm.edu/cems/job_internship_resources">https://www.uvm.edu/cems/job_internship_resources</a></li>
	  <li><a href="https://www.uvm.edu/cems/internship_testimonials">https://www.uvm.edu/cems/internship_testimonials</a></li>
	</ul>

	
	<h2>National Science Foundation REUs</h2>
	<p>The <a href="https://www.nsf.gov/">National Science Foundation</a> (NSF) funds a large number of research opportunities for undergraduate students through its Research Experiences for Undergraduates (REU) Sites program. An REU Site consists of a group of ten or so undergraduates who work in the research programs of the host institution. Each student is associated with a specific research project, where he/she works closely with the faculty and other researchers. Students are granted stipends and, in many cases, assistance with housing and travel. Undergraduate students supported with NSF funds must be citizens or permanent residents of the United States or its possessions. An REU Site may be at either a US or foreign location.</p>
	<p>These are 10-week summer programs where you receive a stipend (typically $5,000) to work on research at another school. Housing and meals are typically covered as well. Applications are due between January and March, depending on the program. You can search the list of programs <a href="https://www.nsf.gov/crssprgm/reu/reu_search.jsp">here</a>.</p>

	<h2>Other Summer Programs</h2>
	<ul>
		<li><a href="https://www.nhlbi.nih.gov/node-general/summer-institute-biostatistics">https://www.nhlbi.nih.gov/node-general/summer-institute-biostatistics</a></li>
		<li><a href="http://drsherrirose.org/resources/">http://drsherrirose.org/resources/</a></li>
		<!-- <li><a href="https://www.jefferson.edu/university/jmc/departments/..." >www.jefferson.edu/university/jmc/departments/...</a></li> -->
		<!-- <li><a href="http://www.amalthea-reu.org/">http://www.amalthea-reu.org/</a></li> -->
	</ul>

	

	<h2>Job Database Links</h2>
	
	<ul>
		<li><a href="http://www.stat.uchicago.edu/students/career/jobdatabases.shtml">University of Chicago Job Databases</a></li>
	</ul>
	
	<h2>Fun things to check out</h2>
	<ul>
		<li><a href="http://www.uvm.edu/~mathclub/">UVM Math Club</a></li>
		<li><a href="https://www.causeweb.org/cause/caption-contest/2019">Monthly statistics-themed caption contest</a> by the Consortium for the Advancement of Undergraduate Statistics Education (CAUSE)</li>
		<li>UVM Career Center: what you can do with a degree in ...
			<ul>
				<li><a href="https://www.uvm.edu/~career/?Page=WCIDWAMI_statistics.html">Statistics</a></li>
				<li><a href="https://www.uvm.edu/~career/?Page=WCIDWAMI_mathematics.html">Mathematics</a></li>
			</ul>
		</li>
		<!-- <li>BU Weekly podcasts</li> -->
		<li><a href="https://simplystatistics.org/">Simply Statistics</a>: a blog about statistics</li>
		<li>American Statistical Association (ASA): <a href="http://thisisstatistics.org">This is Statistics</a></li>
		<li><a href="https://statsandstories.net/">https://statsandstories.net/</a></li>
		<li><a href="https://populationhealthexchange.org/library/podcasts/free-associations/">https://populationhealthexchange.org/library/podcasts/free-associations/</a></li>
		<li><a href="https://seeing-theory.brown.edu/">https://seeing-theory.brown.edu/</a></li>
		<li><a href="http://www.ltcconline.net/greenl/java/Statistics/catStatProb/categorizingStatProblems.html">http://www.ltcconline.net/greenl/java/Statistics/catStatProb/categorizingStatProblems.html</a></li>
		<li><a href="http://www.statslife.org.uk/images/pdf/timeline-of-statistics.pdf">http://www.statslife.org.uk/images/pdf/timeline-of-statistics.pdf</a></li>
		<li><a href="https://www.gapminder.org/">https://www.gapminder.org/</a></li>
        <li><a href="https://fivethirtyeight.com/">https://fivethirtyeight.com/</a></li>
        <li><a href="https://www.statistics.com/blog/">https://www.statistics.com/blog/</a></li>
        <li><a href="https://www.statistics.com/news/">https://www.statistics.com/news/</a></li>
        <li><a href="https://www.causeweb.org/cause/">https://www.causeweb.org/cause/</a></li>
        <li><a href="https://www.gapminder.org/videos/the-joy-of-stats/">https://www.gapminder.org/videos/the-joy-of-stats/</a></li>
        <li><a href="http://learning.statistics-is-awesome.org/">http://learning.statistics-is-awesome.org/</a></li>
        <li><a href="https://teaching.statistics-is-awesome.org/">https://teaching.statistics-is-awesome.org/</a></li>
	</ul>
	


	

{% endblock %}

main/templates/main/people.html
{% extends 'main/base.html' %}
{% load staticfiles %}


{% block title %}
People
{% endblock %}

{% block content %}
<h1>People</h1>
<p>The leaders of the Statistics and Data Science club</p>

<!-- Jenny -->
<h2>Jenny Eberling <small class="text-muted">| President</small></h2>
<div class="row">
	<div class="col-md">
		<img class="profile-pic" src="{% static 'main/images/jenny.jpg' %}">
	</div>
	<div class="col">
	  <p>
		I am a third year statistics major with a mathematics minor,
		and I love learning about the different ways we use statistics
		in the UVM community. My primary interest is the statistic
		analysis of the UVM Women's Basketball team, both as a
		researcher and as their number one fan! I also regularly
		attend Stat Journal Club and Math Club meetings, so don't be
		afraid to come say hello! When I'm not working on my stat
		homework, you can find me playing the trumpet in the pep-band
		or riding my bike around campus.
	  </p>
	</div>
</div>

<!-- Katherine -->
<h2>Katherine Merrill, M.S., Senior Lecturer<small class="text-muted">| Advisor</small></h2>
<div class="row">
	<div class="col-md">
		<img class="profile-pic" src="{% static 'main/images/katherine.jpg' %}">
	</div>
	<div class="col">
	  <p>
		I attended the Ohio State University for my undergraduate
		studies in the early 1980's. At the time, there was a new
		major called Mathematical Sciences, where you studied
		Mathematics, Statistics, and Computer Science -- sound
		familiar? -- Data Science today! I was fortunate enough to
		have taken classes in Statistics with D. Ransom Whitney
		(Mann-Whitney U Test). Here are a couple of links about
		Professor Whitney:
	  <ul>
		<li><a href="https://kb.osu.edu/handle/1811/24142">https://kb.osu.edu/handle/1811/24142</a></li>
		<li><a href="https://www.sciencedirect.com/science/article/pii/B9780126045406500073">https://www.sciencedirect.com/science/article/pii/B9780126045406500073</a></li>
	  </ul>
	  <p>
		I worked at Western Electric in Software Quality Control for 8
		years after receiving my B.S. in Mathematics from OSU. I
		received my M.A. in Statistics from Boston University in 1988.
		I also have my M.S. in Mathematics. Love being in school too
		much?? Yes! Here at UVM, I teach different levels of
		introductory Statistics to many students of varying majors. I
		enjoy sharing my passion of Statistics with you!
	  </p>
	</div>
</div>

<!-- Jacob -->
<h2>Jacob Martin <small class="text-muted">| Advisor</small></h2>
<div class="row">
	<div class="col-md">
		<img class="profile-pic" src="{% static 'main/images/jacob.png' %}">
	</div>
	<div class="col">
		<p></p>
	</div>
</div>
{% endblock %}

main/templates/main/software.html
{% extends 'main/base.html' %}

{% block title %}
Statistical Software
{% endblock %}

{% block content %}
	<h1>Statistical Software</h1>

	<h2>Open Source Software</h2>

	<p><a href="https://www.r-project.org/">R</a> is an open-source statistical software package that is free to use. The recommended developent environment for R is <a href="https://www.rstudio.com/">RStudio</a>.</p>



	
	<h2>UVM Licensed Software</h2>
	<p>UVM has licenses for several statistical software packages. You can find links to download the software <a href="https://www.uvm.edu/software/">here</a> (you'll need to log in with your NetID). Here's links to information about the packages that UVM offers:</p>
	<ul>
		<li><a href="https://www.jmp.com/en_us/home.html">JMP</a></li>
		<li><a href="https://www.wolfram.com/mathematica/">Mathematica</a></li>
		<li><a href="https://www.mathworks.com/products/matlab.html">MATLAB</a></li>
		<li><a href="https://www.ibm.com/analytics/spss-statistics-software">SPSS</a></li>
		<li><a href="https://www.stata.com/">Stata</a></li>
		<li><a href="https://www.graphpad.com/scientific-software/prism/">GraphPad Prism</a></li>	
	</ul>


{% endblock %}